# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import yolo_pb2 as yolo__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in yolo_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class YoloServiceStub:
    """Dịch vụ AI cho Computer Vision
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamPredict = channel.stream_stream(
                '/yolo.YoloService/StreamPredict',
                request_serializer=yolo__pb2.VideoFrame.SerializeToString,
                response_deserializer=yolo__pb2.InferenceResult.FromString,
                _registered_method=True)


class YoloServiceServicer:
    """Dịch vụ AI cho Computer Vision
    """

    def StreamPredict(self, request_iterator, context):
        """Bi-directional stream: Client gửi luồng ảnh liên tục, Server tính và trả kết quả liên tục
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_YoloServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamPredict': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamPredict,
                    request_deserializer=yolo__pb2.VideoFrame.FromString,
                    response_serializer=yolo__pb2.InferenceResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'yolo.YoloService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('yolo.YoloService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class YoloService:
    """Dịch vụ AI cho Computer Vision
    """

    @staticmethod
    def StreamPredict(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/yolo.YoloService/StreamPredict',
            yolo__pb2.VideoFrame.SerializeToString,
            yolo__pb2.InferenceResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
