# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: yolo.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'yolo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nyolo.proto\x12\x04yolo\"3\n\nVideoFrame\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\"`\n\x0b\x42oundingBox\x12\n\n\x02x1\x18\x01 \x01(\x05\x12\n\n\x02y1\x18\x02 \x01(\x05\x12\n\n\x02x2\x18\x03 \x01(\x05\x12\n\n\x02y2\x18\x04 \x01(\x05\x12\x12\n\nconfidence\x18\x05 \x01(\x02\x12\r\n\x05label\x18\x06 \x01(\t\"F\n\x0fInferenceResult\x12 \n\x05\x62oxes\x18\x01 \x03(\x0b\x32\x11.yolo.BoundingBox\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x32M\n\x0bYoloService\x12>\n\rStreamPredict\x12\x10.yolo.VideoFrame\x1a\x15.yolo.InferenceResult\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'yolo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VIDEOFRAME']._serialized_start=20
  _globals['_VIDEOFRAME']._serialized_end=71
  _globals['_BOUNDINGBOX']._serialized_start=73
  _globals['_BOUNDINGBOX']._serialized_end=169
  _globals['_INFERENCERESULT']._serialized_start=171
  _globals['_INFERENCERESULT']._serialized_end=241
  _globals['_YOLOSERVICE']._serialized_start=243
  _globals['_YOLOSERVICE']._serialized_end=320
# @@protoc_insertion_point(module_scope)
